export const SCANNER_DB_POOL = Symbol("SCANNER_DB_POOL");
export const KALSHI_VENUE_CLIENT = Symbol("KALSHI_VENUE_CLIENT");
export const POLYMARKET_VENUE_CLIENT = Symbol("POLYMARKET_VENUE_CLIENT");
export const SCANNER_REPOSITORY = Symbol("SCANNER_REPOSITORY");
export const LLM_EVALUATION_REPOSITORY = Symbol("LLM_EVALUATION_REPOSITORY");
export const SCANNER_LLM_GATEWAY = Symbol("SCANNER_LLM_GATEWAY");
